Global:
  pretrained_model: D:\code\Python\PaddleOCR\PaddleOCR\train\student.pdparams
  epoch_num: 500
  log_smooth_window: 20
  print_batch_step: 20
  save_model_dir: D:\code\Python\PaddleOCR\PaddleOCR\output\rec_ppocr_v4_hgnet
  save_epoch_step: 50
  eval_batch_step: [0, 1000]
  cal_metric_during_train: false
  checkpoints: null
  save_inference_dir: null

Optimizer:
  name: Adam
  lr:
    name: Piecewise
    decay_epochs: [300, 400]  # 根據識別模型的訓練周期調整
    values: [0.001, 0.0001, 0.00001]
    warmup_epoch: 5

Metric:
  name: RecMetric
  main_indicator: acc  # 使用準確度作為主要指標

Train:
  dataset:
    name: SimpleDataSet
    data_dir: D:\code\Python\PaddleOCR\PaddleOCR\train\train_data\images
    label_file_list: [D:\code\Python\PaddleOCR\PaddleOCR\train\train_data\outPart60DictLabel20.txt]
    ratio_list: [1.0]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
          max_text_length: 25  # 根據數據集調整
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label']
  loader:
    shuffle: True
    drop_last: False
    batch_size_per_card: 128
    num_workers: 8

Architecture:
  # name: CRNN  # 將 RecModel 改為 CRNN，這是 PaddleOCR 支持的識別模型名稱
  algorithm: CRNN
  model_type: rec
  Backbone:
    name: MobileNetV3
    scale: 0.5
    model_name: small
    small_stride: [1, 2, 2, 2]
  Neck:
    name: SequenceEncoder
    encoder_type: rnn
    hidden_size: 48
  Head:
    name: CTCHead
    fc_decay: 0.00001


Eval:
  dataset:
    name: SimpleDataSet
    data_dir: D:\code\Python\PaddleOCR\PaddleOCR\train\eval_data\images
    label_file_list: [D:\code\Python\PaddleOCR\PaddleOCR\train\eval_data\label.txt]
    transforms:
      - DecodeImage:
          img_mode: BGR
          channel_first: false
      - CTCLabelEncode:
          max_text_length: 25
      - RecResizeImg:
          image_shape: [3, 32, 100]
      - KeepKeys:
          keep_keys: ['image', 'label']
  loader:
    shuffle: False
    drop_last: False
    batch_size_per_card: 128
    num_workers: 4

PostProcess:
  name: CTCLabelDecode
  max_text_length: 55
  character_dict_path: D:\code\Python\PaddleOCR\PaddleOCR\ppocr\utils\ppocr_keys_v1.txt  # 字典文件
  use_space_char: False

Loss:
  name: CTCLoss


# Global:
#   debug: false
#   use_gpu: true
#   epoch_num: 200
#   log_smooth_window: 20
#   print_batch_step: 10
#   save_model_dir: ./output/rec_ppocr_v4_hgnet
#   save_epoch_step: 10
#   eval_batch_step: [0, 2000]
#   cal_metric_during_train: true
#   pretrained_model: ./train/best_accuracy.pdparams
#   checkpoints:
#   save_inference_dir:
#   use_visualdl: false
#   infer_img: doc/imgs_words/ch/word_1.jpg
#   character_dict_path: ppocr/utils/ppocr_keys_v1.txt
#   max_text_length: &max_text_length 25
#   infer_mode: false
#   use_space_char: true
#   distributed: true
#   save_res_path: ./output/rec/predicts_ppocrv3.txt

# Optimizer:
#   name: Adam
#   beta1: 0.9
#   beta2: 0.999
#   lr:
#     name: Cosine
#     learning_rate: 0.001
#     warmup_epoch: 5
#   regularizer:
#     name: L2
#     factor: 3.0e-05

# Architecture:
#   model_type: rec
#   algorithm: SVTR_HGNet
#   Transform:
#   Backbone:
#     name: PPHGNet_small
#   Head:
#     name: MultiHead
#     head_list:
#       - CTCHead:
#           Neck:
#             name: svtr
#             dims: 120
#             depth: 2
#             hidden_dims: 120
#             kernel_size: [1, 3]
#             use_guide: True
#           Head:
#             fc_decay: 0.00001
#       - NRTRHead:
#           nrtr_dim: 384
#           max_text_length: *max_text_length

# Loss:
#   name: MultiLoss
#   loss_config_list:
#     - CTCLoss:
#     - NRTRLoss:

# PostProcess:  
#   name: CTCLabelDecode

# Metric:
#   name: RecMetric
#   main_indicator: acc

# Train:
#   dataset:
#     name: MultiScaleDataSet
#     ds_width: false
#     data_dir: .\train\train_data\images # 請將此路徑改為您的訓練數據路徑
#     ext_op_transform_idx: 1
#     label_file_list:
#     -  [.\train\train_data\outPart60DictLabel20.txt] # 請將此改為您的訓練數據標籤文件
#     transforms:
#     - DecodeImage:
#         img_mode: BGR
#         channel_first: false
#     - RecConAug:
#         prob: 0.5
#         ext_data_num: 2
#         image_shape: [48, 320, 3]
#         max_text_length: *max_text_length
#     - RecAug:
#     - MultiLabelEncode:
#         gtc_encode: NRTRLabelEncode
#     - KeepKeys:
#         keep_keys:
#         - image
#         - label_ctc
#         - label_gtc
#         - length
#         - valid_ratio
#   sampler:
#     name: MultiScaleSampler
#     scales: [[320, 32], [320, 48], [320, 64]]
#     first_bs: &bs 128
#     fix_bs: false
#     divided_factor: [8, 16] # w, h
#     is_training: True
#   loader:
#     shuffle: true
#     batch_size_per_card: *bs
#     drop_last: true
#     num_workers: 8

# Eval:
#   dataset:
#     name: SimpleDataSet
#     data_dir: ./train/eval_data/images
#     label_file_list:
#     - [./train/eval_data/label.txt]
#     transforms:
#     - DecodeImage:
#         img_mode: BGR
#         channel_first: false
#     - MultiLabelEncode:
#         gtc_encode: NRTRLabelEncode
#     - RecResizeImg:
#         image_shape: [3, 48, 320]
#     - KeepKeys:
#         keep_keys:
#         - image
#         - label_ctc
#         - label_gtc
#         - length
#         - valid_ratio
#   loader:
#     shuffle: false
#     drop_last: false
#     batch_size_per_card: 128
#     num_workers: 4
